name: test
on: [push]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install json library
      run: sudo apt install libjson-c-dev
    - name: esegui
      run: chmod +x compile.sh && ./compile.sh
