name: test
on: [push]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install
      run: sudo apt install libjson-c-dev cmake
    - name: install wjelement
      run:  git clone https://github.com/netmail-open/wjelement && cd wjelement && sudo cmake -DLIB_DEST_DIR=/usr/local/lib64 && sudo make && sudo make install
    - name: esegui
      run: chmod +x compile.sh && ./compile.sh
      

