name: test
on: [push]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install libjson
      run: sudo apt install libjson-c-dev cmake
    - name: install wjelement
      run:  git clone https://github.com/netmail-open/wjelement && cd wjelement && sudo cmake -DLIB_DEST_DIR=/usr/local/lib64 && sudo make && sudo make install
    - name: create documentation
      run: git clone https://github.com/doxygen/doxygen.git && cd doxygen && mkdir build && cd build && sudo cmake -G "Unix Makefiles" .. && sudo make && sudo make install && doxygen -g Doxyfile && doxygen Doxyfile && cd html && cat index.html

