name: test
on: [push]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install libjson
      run: sudo apt install libjson-c-dev cmake
    - name: install wjelement
      run:  git clone https://github.com/netmail-open/wjelement && cd wjelement && sudo cmake -DLIB_DEST_DIR=/usr/local/lib64 && sudo make && sudo make install
    - name: create documentation
      run: gunzip doxygen-$VERSION.src.tar.gz && tar xf doxygen-$VERSION.src.tar cd doxygen-$VERSION && mkdir build && cd build && cmake -G "Unix Makefiles" ..
      

